<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    @template.styles()
</head>
<body>
<header>
    <h1>Organisation des Événements</h1>
    <div class="menu-container">
        <button class="menu-button"></button>
        <div class="dropdown-menu">
            <a href="/events">🎉 Voir les Événements</a>
            <a href="/benefits">🎁 Voir les Bénéfices</a>
        </div>
    </div>
</header>

<main>
    <h1>Explorez nos fonctionnalités</h1>
    <p>
        Bienvenue sur notre plateforme ! Découvrez des événements passionnants, gérez vos utilisateurs, et accédez à
        des avantages exclusifs. Naviguez à travers nos différentes sections pour en savoir plus.
    </p>
    <p>
        Nous proposons une interface intuitive et des fonctionnalités enrichies pour faciliter votre gestion des
        événements. Profitez dès maintenant de notre expérience unique !
    </p>
</main>

<footer>
    &copy; 2025 - Organisation des Événements by HEIG-VD
</footer>
</body>
</html>
